<a href="https://colab.research.google.com/github/bullimohanreddy/mo./blob/main/bullimohan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Women Cloth Reviews Prediction with Multi Nomial Naive Bayes

The multinomial Naive Bayes classiffier is suitable for classification eith discrete features.The multinomial distribution normally requires integer feature counts.However,in practicee,fractional counts such as tf-idf may also work

Import Library

In [36]:
import pandas as pd

In [37]:
import numpy as np

In [38]:
import matplotlib.pyplot as plt

Import Dataset

In [39]:
df = pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Teaching-Data/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [40]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [42]:
df.shape

(23486, 10)

Missing Values

Remove missing values in Reviews columns with No Review Text

In [43]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [44]:
df[df['Review']==""]=np.NaN

In [45]:
df['Review'].fillna("No Review",inplace=True)

In [46]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [47]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

Define Target(y) and Feature (x)

In [48]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [49]:
X = df['Review']

In [50]:
y = df['Rating']

In [51]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.7,stratify = y,random_state =2529)

In [ ]:
X_train.shape,X_test.shape, y_train.shape, y_test.shape

((7045,), (16441,), (7045,), (16441,))

Get Feature Text Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(lowercase = True, analyzer='word',ngram_range=(2, 3), stop_words = 'english', max_features=5000)

In [ ]:
X_train = cv.fit_transform(X_train)

In [52]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 dress', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test = cv.fit_transform(X_test)

In [53]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 dress', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [54]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Get Model Train

In [55]:
from sklearn.naive_bayes import MultinomialNB

In [56]:
model = MultinomialNB()

In [59]:
model.fit(X_train,y_train)

MultinomialNB()

MultinomialNB()

Get Model Trediction

In [60]:
y_pred = model.predict(X_test)

In [61]:
y_pred.shape

(16441,)

In [63]:
y_pred

array([3., 4., 2., ..., 5., 4., 3.])

array([3., 4., 2., ..., 5., 4., 3.])

Get Probability of Each Predicted Class

In [65]:
model.predict_proba(X_test)

array([[2.50243939e-01, 1.21534354e-01, 4.79327448e-01, 1.27392454e-02,
        1.36155013e-01],
       [7.07567572e-02, 4.58818848e-02, 2.63088820e-01, 6.12325394e-01,
        7.94714345e-03],
       [2.01162807e-01, 3.38200504e-01, 2.95746505e-01, 9.24481824e-02,
        7.24420016e-02],
       ...,
       [3.91842500e-03, 2.98245742e-03, 3.09715894e-04, 7.72959108e-03,
        9.85059811e-01],
       [1.61530659e-01, 3.51476805e-02, 5.52149762e-02, 5.43909305e-01,
        2.04197379e-01],
       [1.26442837e-01, 4.89792929e-02, 3.28750971e-01, 2.68648730e-01,
        2.27178169e-01]])

array([[2.50243939e-01, 1.21534354e-01, 4.79327448e-01, 1.27392454e-02,
        1.36155013e-01],
       [7.07567572e-02, 4.58818848e-02, 2.63088820e-01, 6.12325394e-01,
        7.94714345e-03],
       [2.01162807e-01, 3.38200504e-01, 2.95746505e-01, 9.24481824e-02,
        7.24420016e-02],
       ...,
       [3.91842500e-03, 2.98245742e-03, 3.09715894e-04, 7.72959108e-03,
        9.85059811e-01],
       [1.61530659e-01, 3.51476805e-02, 5.52149762e-02, 5.43909305e-01,
        2.04197379e-01],
       [1.26442837e-01, 4.89792929e-02, 3.28750971e-01, 2.68648730e-01,
        2.27178169e-01]])

Get Model Evalution

In [69]:
from sklearn.metrics import confusion_matrix, classification_report

In [74]:
print(confusion_matrix(y_test, y_pred))

[[  37   76   66  130  280]
 [  83  166  182  203  462]
 [ 196  285  342  396  791]
 [ 386  392  457  695 1624]
 [ 885  837  963 1584 4923]]


In [75]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.06      0.03       589
         2.0       0.09      0.15      0.12      1096
         3.0       0.17      0.17      0.17      2010
         4.0       0.23      0.20      0.21      3554
         5.0       0.61      0.54      0.57      9192

    accuracy                           0.37     16441
   macro avg       0.23      0.22      0.22     16441
weighted avg       0.42      0.37      0.39     16441



Recategories Ratings as Poor (0) and Good (1)

In [78]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

1.0    18208
0.0     5278
Name: Rating, dtype: int64

Re-Rating as 1,2,3 as 0 and 4,5 as 1

In [81]:
df.replace({'Rating' :{1:0,2:0,3:0,4:1,5:1}},inplace = True)

In [82]:
y = df['Rating']

In [83]:
X = df['Review']

Train Test Split

In [85]:
from sklearn.model_selection import train_test_split

In [86]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.7,stratify = y,random_state =2529)

In [88]:
X_train.shape,X_test.shape, y_train.shape, y_test.shape

((7045,), (16441,), (7045,), (16441,))

((7045,), (16441,), (7045,), (16441,))

Get Feature Text Conversion to Tokens

In [89]:
from sklearn.feature_extraction.text import CountVectorizer

In [90]:
cv = CountVectorizer(lowercase = True, analyzer='word',ngram_range=(2, 3), stop_words = 'english', max_features=5000)

In [91]:
X_train = cv.fit_transform(X_train)

In [92]:
X_test = cv.fit_transform(X_test)

Get Model Re-Train

In [93]:
from sklearn.naive_bayes import MultinomialNB

In [97]:
model = MultinomialNB()

In [98]:
model.fit(X_train, y_train)

MultinomialNB()

Get Model Prediction

In [99]:
y_pred = model.predict(X_test)

In [100]:
y_pred.shape

(16441,)

In [101]:
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

Get Model Evalution

In [103]:
from sklearn.metrics import confusion_matrix, classification_report

In [106]:
print(confusion_matrix(y_test,y_pred))

[[16441]]


In [107]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     16441

    accuracy                           1.00     16441
   macro avg       1.00      1.00      1.00     16441
weighted avg       1.00      1.00      1.00     16441

